// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9qQo7F24tlyHYTZrsjz8SYlkmmch4b38',
    appId: '1:152719791153:web:5d009f38ad5241a1c27110',
    messagingSenderId: '152719791153',
    projectId: 'flutter-prep-2a4b5',
    authDomain: 'flutter-prep-2a4b5.firebaseapp.com',
    databaseURL: 'https://flutter-prep-2a4b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2a4b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyV-KNQsnz-hWH5Xa4Q0X9BNV0be-aeNk',
    appId: '1:152719791153:android:e7a2fd8fd9ddea28c27110',
    messagingSenderId: '152719791153',
    projectId: 'flutter-prep-2a4b5',
    databaseURL: 'https://flutter-prep-2a4b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2a4b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjan-HsyhLNW_su9lDTIboiHwLcNrNtZc',
    appId: '1:152719791153:ios:399b31f5267d8620c27110',
    messagingSenderId: '152719791153',
    projectId: 'flutter-prep-2a4b5',
    databaseURL: 'https://flutter-prep-2a4b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2a4b5.appspot.com',
    iosBundleId: 'com.example.testingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjan-HsyhLNW_su9lDTIboiHwLcNrNtZc',
    appId: '1:152719791153:ios:399b31f5267d8620c27110',
    messagingSenderId: '152719791153',
    projectId: 'flutter-prep-2a4b5',
    databaseURL: 'https://flutter-prep-2a4b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2a4b5.appspot.com',
    iosBundleId: 'com.example.testingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9qQo7F24tlyHYTZrsjz8SYlkmmch4b38',
    appId: '1:152719791153:web:561549d79ac8db32c27110',
    messagingSenderId: '152719791153',
    projectId: 'flutter-prep-2a4b5',
    authDomain: 'flutter-prep-2a4b5.firebaseapp.com',
    databaseURL: 'https://flutter-prep-2a4b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2a4b5.appspot.com',
  );
}
